import 'bootstrap/dist/css/bootstrap.min.css'
import '@/6_shared/style/style.scss'
import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'
import Header from '@/3_widgets/general/Header'
import { ProviderRedux } from '@/6_shared/store/provider'
import React from 'react'
import { persistStore } from 'redux-persist'
import { store } from '@/6_shared/store/store'

const nunitoSans = Nunito_Sans({ subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
    title: 'CryptoQuick | Coins',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={nunitoSans.className}>
                <main>
                    <ProviderRedux>
                        <Header />
                        {children}
                    </ProviderRedux>
                </main>
            </body>
        </html>
    )
}
